#!/bin/ksh
#This shell script is written by Sangharatna Godboley
#Important Note: Before running this tool KLEEMA you require to install KLEE or any other DSE.
#In this version of KLEEMA we installed KLEE and TracerX from https://tracer-x.github.io/gettingstarted.
#After installation kindly change the path in klee.sh and mutator.sh from "/home/sanghu/TracerX/" to your home path.  


export BENCHMARK=$1
export toolValue=$2

#The below command is to run KLEE or any other DSE 
./klee.sh $BENCHMARK $toolValue

#The below command is to run the mutator script to create the mutants
python mutator.py $BENCHMARK.c $BENCHMARK-Mutants

#The below command is to run the identify the dead mutants and avoid to run them,
#this is done with the information of Lines covered, gathered from the KLEE or DSE. 
./deadmutants.sh $BENCHMARK $toolValue

#The below command is to run each reachable mutant with test inputs generated by KLEE or DSE
./mutator.sh $BENCHMARK

#The below commands are useful to collect the important information for analysis purposes
mkdir $BENCHMARK-RESULTS
mv ${BENCHMARK}-KLEE-FILES $BENCHMARK-RESULTS
mv Mutant-compilable-check.txt $BENCHMARK-RESULTS
mv killed-Mutants-report.txt $BENCHMARK-RESULTS
mv $BENCHMARK-ReachedMutantsList.txt $BENCHMARK-RESULTS
mv $BENCHMARK-DeadMutantsList.txt $BENCHMARK-RESULTS
mv $BENCHMARK-report.txt $BENCHMARK-RESULTS
mv $BENCHMARK-Mutants $BENCHMARK-RESULTS
cp $BENCHMARK.c $BENCHMARK-RESULTS
mv $BENCHMARK-ReachedMutants $BENCHMARK-RESULTS

rm -r *.bc
rm -r *.i
rm -r *.o
